package pktest.data.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.List;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.Property;

import pktest.data.Address;

/**
 * Class _Person was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Person extends BaseDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<List<Address>> ADDRESSES = Property.create("addresses", List.class);
    public static final Property<Address> LATEST_ADDRESS = Property.create("latestAddress", Address.class);

    protected String name;

    protected Object addresses;
    protected Object latestAddress;

    public void setName(String name) {
        beforePropertyWrite("name", this.name, name);
        this.name = name;
    }

    public String getName() {
        beforePropertyRead("name");
        return this.name;
    }

    public void addToAddresses(Address obj) {
        addToManyTarget("addresses", obj, true);
    }

    public void removeFromAddresses(Address obj) {
        removeToManyTarget("addresses", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<Address> getAddresses() {
        return (List<Address>)readProperty("addresses");
    }

    public void setLatestAddress(Address latestAddress) {
        setToOneTarget("latestAddress", latestAddress, true);
    }

    public Address getLatestAddress() {
        return (Address)readProperty("latestAddress");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "name":
                return this.name;
            case "addresses":
                return this.addresses;
            case "latestAddress":
                return this.latestAddress;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "name":
                this.name = (String)val;
                break;
            case "addresses":
                this.addresses = val;
                break;
            case "latestAddress":
                this.latestAddress = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.name);
        out.writeObject(this.addresses);
        out.writeObject(this.latestAddress);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.name = (String)in.readObject();
        this.addresses = in.readObject();
        this.latestAddress = in.readObject();
    }

}
